# Generated by Django 6.0.5 on 2026-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
