# Generated by Django 6.0.5 on 2026-08-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_tasks_updated_date_tasks_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
